Repository sdpython/pyquickhelper, pull requests merged in 2022-07, with the labels that each got.

#371 Improves logging calls
  src/pyquickhelper/helpgen/sphinxm_convert_doc_sphinx_helper.py
  src/pyquickhelper/pycode/utils_tests.py
  src/pyquickhelper/sphinxext/_sphinx_common_builder.py
  src/pyquickhelper/sphinxext/sphinx_autosignature.py
  src/pyquickhelper/sphinxext/sphinx_bigger_extension.py
  src/pyquickhelper/sphinxext/sphinx_blog_extension.py
  src/pyquickhelper/sphinxext/sphinx_cmdref_extension.py
  src/pyquickhelper/sphinxext/sphinx_docassert_extension.py
  src/pyquickhelper/sphinxext/sphinx_doctree_builder.py
  src/pyquickhelper/sphinxext/sphinx_downloadlink_extension.py
  src/pyquickhelper/sphinxext/sphinx_gdot_extension.py
  src/pyquickhelper/sphinxext/sphinx_gitlog_extension.py
  src/pyquickhelper/sphinxext/sphinx_image_extension.py
  src/pyquickhelper/sphinxext/sphinx_latex_builder.py
  src/pyquickhelper/sphinxext/sphinx_md_builder.py
  src/pyquickhelper/sphinxext/sphinx_postcontents_extension.py
  src/pyquickhelper/sphinxext/sphinx_quote_extension.py
  src/pyquickhelper/sphinxext/sphinx_rst_builder.py
  src/pyquickhelper/sphinxext/sphinx_tocdelay_extension.py
  src/pyquickhelper/sphinxext/sphinx_toctree_extension.py
  src/pyquickhelper/sphinxext/sphinx_video_extension.py
  src/pyquickhelper/sphinxext/sphinx_youtube_extension.py
Labels: code

#372 Adds missing argument env in dummy application sphinx builder
  _unittests/ut_helpgen/test_rst2html.py
  _unittests/ut_sphinxext/test_autosignature.py
  _unittests/ut_sphinxext/test_autosignature_bug.py
  _unittests/ut_sphinxext/test_bigger_extension.py
  _unittests/ut_sphinxext/test_blocref_extension.py
  _unittests/ut_sphinxext/test_blog_extension.py
  _unittests/ut_sphinxext/test_blog_helper.py
  _unittests/ut_sphinxext/test_blog_list.py
  _unittests/ut_sphinxext/test_bokeh_extension.py
  _unittests/ut_sphinxext/test_builders_missing.py
  _unittests/ut_sphinxext/test_cmdref_extension.py
  _unittests/ut_sphinxext/test_collapse_extension.py
  _unittests/ut_sphinxext/test_doc_bug.py
  _unittests/ut_sphinxext/test_docassert.py
  _unittests/ut_sphinxext/test_doctree_builder.py
  _unittests/ut_sphinxext/test_downloadlink_extension.py
  _unittests/ut_sphinxext/test_epkg_extension.py
  _unittests/ut_sphinxext/test_exref_extension.py
  _unittests/ut_sphinxext/test_ext_helper.py
  _unittests/ut_sphinxext/test_faqref_extension.py
  _unittests/ut_sphinxext/test_gdot_extension.py
  _unittests/ut_sphinxext/test_githublink_extension.py
  _unittests/ut_sphinxext/test_gitlog_extension.py
  _unittests/ut_sphinxext/test_image_extension.py
  _unittests/ut_sphinxext/test_import_any_object.py
  _unittests/ut_sphinxext/test_latex_builder.py
  _unittests/ut_sphinxext/test_mathdef_extension.py
  _unittests/ut_sphinxext/test_md_builder.py
  _unittests/ut_sphinxext/test_nbref_extension.py
  _unittests/ut_sphinxext/test_postcontents_extension.py
  _unittests/ut_sphinxext/test_quote_extension.py
  _unittests/ut_sphinxext/test_revealsjs_directives.py
  _unittests/ut_sphinxext/test_rst_builder.py
  _unittests/ut_sphinxext/test_runpython_code_block.py
  _unittests/ut_sphinxext/test_runpython_context.py
  _unittests/ut_sphinxext/test_runpython_extension.py
  _unittests/ut_sphinxext/test_runpython_extension_image.py
  _unittests/ut_sphinxext/test_runpython_extension_toggle.py
  _unittests/ut_sphinxext/test_runpython_store_in_file.py
  _unittests/ut_sphinxext/test_sharenet_extension.py
  _unittests/ut_sphinxext/test_simpleimage_extension.py
  _unittests/ut_sphinxext/test_style_doc.py
  _unittests/ut_sphinxext/test_template_extension.py
  _unittests/ut_sphinxext/test_thumbnail_extension.py
  _unittests/ut_sphinxext/test_tocdelay_extension.py
  _unittests/ut_sphinxext/test_todoext_extension.py
  _unittests/ut_sphinxext/test_video_extension.py
  _unittests/ut_sphinxext/test_youtube_extension.py
  src/pyquickhelper/helpgen/sphinxm_convert_doc_sphinx_helper.py
  src/pyquickhelper/sphinxext/sphinx_latex_builder.py
Labels: bug

#373 Improves results aftrer running the unit tests, calls sys.exit with a different code
  src/pyquickhelper/pycode/setup_helper.py
  src/pyquickhelper/pycode/utils_tests.py
  src/quicksetup/pyquicksetup/__init__.py
  src/quicksetup/pyquicksetup/pyquick.py
Labels: bug, CI

#374 Improves unit test summary report
  src/pyquickhelper/pycode/utils_tests_private.py
  src/quicksetup/pyquicksetup/__init__.py
  src/quicksetup/pyquicksetup/pyquick.py
Labels: CI

#375 Reduces the number of warnings
  _unittests/ut_cli/test_cli_ftp.py
  _unittests/ut_cli/test_cli_sphinx_rst.py
  _unittests/ut_helpgen/test_conf_sphinx.py
  _unittests/ut_ipythonhelper/test_notebook_runner_empty.py
  _unittests/ut_jenkinshelper/test_yaml_jenkins_split.py
  _unittests/ut_loghelper/test_run_cmd.py
  src/pyquickhelper/filehelper/ftp_transfer.py
  src/pyquickhelper/jenkinshelper/yaml_helper.py
  src/pyquickhelper/loghelper/run_cmd.py
Labels: CI
